- name: update os
  yum:
    name: '*'
    state: latest
  register: output
  when: ansible_os_family == "RedHat"
  notify:
  - yum log to file

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ my_packages }}"